# Generated by Django 4.1.4 on 2023-01-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_upcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('date', models.CharField(max_length=100)),
                ('subject', models.TextField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
