# Generated by Django 4.1.4 on 2023-01-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=100)),
                ('point', models.CharField(max_length=50)),
                ('win', models.CharField(max_length=50)),
                ('lose', models.CharField(max_length=50)),
                ('draw', models.CharField(max_length=50)),
            ],
        ),
    ]
