# Generated by Django 4.1.4 on 2023-01-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_finale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wcup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='media')),
                ('image2', models.ImageField(upload_to='media')),
                ('country1', models.CharField(max_length=100)),
                ('country2', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
            ],
        ),
    ]
